[package]
name = "weather"
version = "0.0.1"
edition = "2024"

[dependencies]
# reqwest = { version = "0.12.12", features = ["blocking", "json"] }
reqwest = { version = "0.12.23", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"